# Generated by Django 2.0.2 on 2018-03-04 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('age', models.IntegerField(default=0)),
                ('gender', models.CharField(choices=[(1, 'male'), (2, 'female'), (3, 'other')], max_length=100)),
                ('link', models.TextField(default='')),
                ('description', models.TextField(default='')),
                ('cast_type', models.CharField(choices=[(1, 'actor'), (2, 'director'), (3, 'producer')], max_length=100)),
            ],
        ),
    ]
