# Generated by Django 2.0.2 on 2018-03-05 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_system', '0003_auto_20180305_0014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='cast',
            new_name='casts',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='genre',
            new_name='genres',
        ),
    ]
