# Generated by Django 2.0.3 on 2018-03-25 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking_system', '0006_auto_20180325_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking_system.Language'),
        ),
    ]
