# Generated by Django 2.0.3 on 2018-03-27 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking_system', '0008_auto_20180327_1236'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrewProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('age', models.IntegerField(default=0)),
                ('link', models.TextField(default='')),
                ('description', models.TextField(default='')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking_system.Gender')),
            ],
        ),
        migrations.CreateModel(
            name='MovieCrew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking_system.CrewProfile')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking_system.CastType')),
            ],
        ),
        migrations.RemoveField(
            model_name='cast',
            name='cast_type',
        ),
        migrations.RemoveField(
            model_name='cast',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='casts',
        ),
        migrations.DeleteModel(
            name='Cast',
        ),
        migrations.AddField(
            model_name='movie',
            name='crew',
            field=models.ManyToManyField(to='booking_system.MovieCrew'),
        ),
    ]
