# Generated by Django 2.0.3 on 2018-03-31 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_system', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='release_date',
        ),
    ]
