# Generated by Django 2.0.2 on 2018-03-05 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_system', '0002_auto_20180305_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cast',
            name='cast_type',
            field=models.IntegerField(choices=[(1, 'actor'), (2, 'director'), (3, 'producer')]),
        ),
        migrations.AlterField(
            model_name='cast',
            name='gender',
            field=models.IntegerField(choices=[(1, 'male'), (2, 'female'), (3, 'other')]),
        ),
        migrations.AlterField(
            model_name='movie',
            name='language',
            field=models.IntegerField(choices=[(0, 'english'), (1, 'hindi'), (2, 'telugu')]),
        ),
    ]
