# Generated by Django 2.0.3 on 2018-03-31 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_system', '0002_remove_movie_release_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='imdb_id',
        ),
    ]
