# Generated by Django 2.0.3 on 2018-03-27 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking_system', '0007_auto_20180325_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='CastType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='cast',
            name='cast_type',
        ),
        migrations.AlterField(
            model_name='cast',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking_system.Gender'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking_system.Gender'),
        ),
        migrations.AddField(
            model_name='cast',
            name='cast_type',
            field=models.ManyToManyField(to='booking_system.CastType'),
        ),
    ]
