# Generated by Django 2.0.2 on 2018-03-29 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking_system', '0011_auto_20180329_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='status',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='booking_system.StatusType'),
        ),
    ]
