# Generated by Django 2.0.2 on 2018-03-29 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking_system', '0013_auto_20180329_0952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='type',
        ),
        migrations.RemoveField(
            model_name='theater',
            name='seat_types',
        ),
        migrations.AddField(
            model_name='seat',
            name='seat_type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='booking_system.SeatType'),
        ),
    ]
